"""empty message

Revision ID: 94542d875d89
Revises: 5034bbfe8f3e
Create Date: 2021-01-27 12:21:25.858370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94542d875d89'
down_revision = '5034bbfe8f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_massage_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_massage_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_message_read_time')
    # ### end Alembic commands ###
